/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Action =
  | {
      duration: number;
      function: "transferLocked";
      qty: string;
      to: string;
      tokenId: string;
    }
  | {
      function: "unlock";
    }
  | {
      function: "configure";
      operators?: string[] | null;
      superOperators?: string[] | null;
    }
  | {
      function: "evolve";
      value: string;
    }
  | {
      actions: Action1[];
      function: "batch";
    };
export type Action1 =
  | {
      duration: number;
      function: "transferLocked";
      qty: string;
      to: string;
      tokenId: string;
    }
  | {
      function: "unlock";
    }
  | {
      function: "configure";
      operators?: string[] | null;
      superOperators?: string[] | null;
    }
  | {
      function: "evolve";
      value: string;
    }
  | {
      actions: Action1[];
      function: "batch";
    };
