/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Action =
  | {
      function: "mintShuffle";
      nfts: ShuffleBaseIds;
      ticker?: string | null;
    }
  | {
      boost?: BoostOpenShuffle | null;
      function: "openShuffle";
      owner?: string | null;
      shuffleId: string;
    }
  | {
      function: "configure";
      operators?: string[] | null;
      superOperators?: string[] | null;
    }
  | {
      function: "evolve";
      value: string;
    }
  | {
      actions: Action1[];
      function: "batch";
    };
export type ShuffleBaseIds =
  | {
      /**
       * @minItems 2
       * @maxItems 2
       */
      legendary: [string, string];
    }
  | {
      /**
       * @minItems 3
       * @maxItems 3
       */
      epic: [string, string, string];
    }
  | {
      /**
       * @minItems 4
       * @maxItems 4
       */
      rare: [string, string, string, string];
    };
export type Action1 =
  | {
      function: "mintShuffle";
      nfts: ShuffleBaseIds;
      ticker?: string | null;
    }
  | {
      boost?: BoostOpenShuffle | null;
      function: "openShuffle";
      owner?: string | null;
      shuffleId: string;
    }
  | {
      function: "configure";
      operators?: string[] | null;
      superOperators?: string[] | null;
    }
  | {
      function: "evolve";
      value: string;
    }
  | {
      actions: Action1[];
      function: "batch";
    };

export interface BoostOpenShuffle {
  /**
   * 0 <= boost <= 1
   */
  boost: number;
  shufflePrice: string;
}
