/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Action =
  | {
      function: "balanceOf";
      target: string;
      tokenId: string;
    }
  | {
      from?: string | null;
      function: "transfer";
      qty: string;
      to: string;
      tokenId: string;
    }
  | {
      function: "configure";
      operators?: string[] | null;
      proxies?: string[] | null;
      superOperators?: string[] | null;
    }
  | {
      approved: boolean;
      function: "setApprovalForAll";
      operator: string;
    }
  | {
      function: "isApprovedForAll";
      operator: string;
      owner: string;
    }
  | {
      function: "evolve";
      value: string;
    }
  | {
      function: "mint";
      prefix?: string | null;
      qty: string;
      ticker?: string | null;
    }
  | {
      function: "burn";
      owner?: string | null;
      qty: string;
      tokenId: string;
    }
  | {
      actions: Action1[];
      function: "batch";
    };
export type Action1 =
  | {
      function: "balanceOf";
      target: string;
      tokenId: string;
    }
  | {
      from?: string | null;
      function: "transfer";
      qty: string;
      to: string;
      tokenId: string;
    }
  | {
      function: "configure";
      operators?: string[] | null;
      proxies?: string[] | null;
      superOperators?: string[] | null;
    }
  | {
      approved: boolean;
      function: "setApprovalForAll";
      operator: string;
    }
  | {
      function: "isApprovedForAll";
      operator: string;
      owner: string;
    }
  | {
      function: "evolve";
      value: string;
    }
  | {
      function: "mint";
      prefix?: string | null;
      qty: string;
      ticker?: string | null;
    }
  | {
      function: "burn";
      owner?: string | null;
      qty: string;
      tokenId: string;
    }
  | {
      actions: Action1[];
      function: "batch";
    };
