/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface State {
  approvals: {
    [k: string]: {
      [k: string]: boolean;
    };
  };
  canEvolve?: boolean | null;
  evolve?: string | null;
  name?: string | null;
  settings: Settings;
  tokens: {
    [k: string]: Token;
  };
}
export interface Settings {
  allowFreeTransfer: boolean;
  operators: string[];
  proxies: string[];
  superOperators: string[];
}
export interface Token {
  balances: {
    [k: string]: string;
  };
  ticker: string;
  txId?: string | null;
}
