[package]
name = "warp-packs"
version = "0.1.0"
authors = ["Eyal Chojnowski <eyal@pianity.com>"]
edition = "2021"

[dependencies]
warp-erc1155 = { path = "../../erc1155/definition" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "=0.8.11"
