/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Action =
  | {
      baseId: string;
      fees: {
        [k: string]: number;
      };
      function: "attachFee";
      rate: number;
    }
  | {
      fees: {
        [k: string]: number;
      };
      function: "mintNft";
      rate: number;
      scarcity: Scarcity;
      ticker?: string | null;
    }
  | {
      from: string;
      function: "transfer";
      price: string;
      to: string;
      tokenId: string;
    }
  | {
      function: "configure";
      operators?: string[] | null;
      superOperators?: string[] | null;
    }
  | {
      function: "evolve";
      value: string;
    }
  | {
      actions: Action1[];
      function: "batch";
    };
export type Scarcity = "unique" | "legendary" | "epic" | "rare";
export type Action1 =
  | {
      baseId: string;
      fees: {
        [k: string]: number;
      };
      function: "attachFee";
      rate: number;
    }
  | {
      fees: {
        [k: string]: number;
      };
      function: "mintNft";
      rate: number;
      scarcity: Scarcity;
      ticker?: string | null;
    }
  | {
      from: string;
      function: "transfer";
      price: string;
      to: string;
      tokenId: string;
    }
  | {
      function: "configure";
      operators?: string[] | null;
      superOperators?: string[] | null;
    }
  | {
      function: "evolve";
      value: string;
    }
  | {
      actions: Action1[];
      function: "batch";
    };
