/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface State {
  attachedFees: {
    [k: string]: AttachedFee;
  };
  canEvolve?: boolean | null;
  evolve?: string | null;
  name?: string | null;
  settings: Settings;
}
export interface AttachedFee {
  baseId: string;
  fees: {
    [k: string]: number;
  };
  rate: number;
}
export interface Settings {
  /**
   * NOTE: Currently only Pianity is allowed to do mints and transfers which means that ownership always defaults to Pianity. This field represents the address to which ownership always defaults in the ERC1155 contract.
   *
   * It is required in order to, for example, determine whether a transfer represents a sell or a resell.
   */
  custodian: string;
  /**
   * Address of the attached ERC1155-compliant contract
   */
  erc1155: string;
  /**
   * Token ID of the token used for paying
   */
  exchangeToken: string;
  operators: string[];
  superOperators: string[];
}
